title: Miji Kim # your name (or website title) here
logo: "/images/miji.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, I'm Miji Kim.  
  <br><br>
  Developer & Data Enthusiast 
  <br><br>
  <a href="https://www.linkedin.com/in/shelkim/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
